version: '3'
services:
  service:
    container_name: "watch_dog"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
  postgres:
    container_name: "db"
    image: "postgres:13"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
