version: "3.8"

services:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always

  redis:
    image: redis:6.0.8-alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/opt
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    restart: always

  periodic:
    build:
      context: .
      dockerfile: docker/Dockerfile.periodic
    container_name: periodic
    env_file:
      - .env
    volumes:
      - .:/opt
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    restart: always

volumes:
  redis_data:
  postgres_data:
